config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get 'home/about' => "homes#about", as: "about"
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :users, only: [:index,:show, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  has_one_attached :image
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_one_attached :profile_image

  validates :name, presence: true, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path),filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100,100]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?
before_action :authenticate_user!, except: [:top, :about]

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @books =Book.all
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = 'You have created book successfully.'
      redirect_to book_path(@book)
    else
      @user = current_user
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    if @book.save
    flash[:notice] = 'You have updated book successfully.'
    redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

 def correct_user
    @book = Book.find(params[:id])
    redirect_to(books_path) unless @book.user == current_user
 end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books.all
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'You have updated user successfully.'
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <p><%= image_tag user.get_profile_image,size: '100x100' %><p>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
            <th>name</th>
            <th><%= user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
          </tr>
        </tbody>
      </table>
      <div class="row">
        <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
          <i class="fas fa-user-cog"></i>
        <% end %>
      </div>
      <h2 class="mt-3">New book</h2>

      <% if book.errors.any? %>
        <%= book.errors.count %>errors prohibited this obj from being saved:
        <ul>
          <% book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>

      <%= form_with model: Book.new do |f| %>
        <p>Title</p>
        <%= f.text_field :title %>

        <p>Opinion</p>
        <%= f.text_area :body %>
        <%= f.submit "Create Book", class: "btn btn-success" %>
      <% end %>
    </div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      
      <% if @book.errors.any? %>
         <%= @book.errors.count %>errors prohibited this obj from being saved:
        <ul>
         <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
         <% end %>
        </ul>
      <% end %>
      
      <%= form_with model: @book do |f| %>
        <laabel for="inputTitle">Title</laabel><br>
        <%= f.text_field :title, autofocus:true, id:"inputTitle"%><br>
        <label for="inputBody">Opinion</label><br>
        <%= f.text_area :body, autofocus:true, id:"inputBody"%><br>
        <%= f.submit "Update Book", class: "btn btn-success" %>
      <% end %>
      
      <p>
        <%= link_to "Show", book_path %>
        |
        <%= link_to "Back", books_path %>
      </p>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<%= render 'books/list', user:@user, book:@book %>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
            <%= link_to user_path(book.user.id) do %>
              <%= image_tag book.user.get_profile_image %>
            <% end %>
            </td>
            <td><%= link_to book.title,book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<%= render 'books/list', user:@user, book:@book %>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= image_tag @book.user.get_profile_image %><br>
              <%= link_to @user.name,user_path(@user.id) %>
            </td>
            <td><%= link_to @book.title,book_path(@book.id) %></td>
            <td><%= @book.body %></td>
            <% if @book.user == current_user %>
            <td>
              <%= link_to edit_book_path(@book.id), class: "btn btn-sm btn-success" do %>
                Edit
              <% end %>
            </td>
            <td>
              <%= link_to book_path(@book.id), class: "btn btn-sm btn-danger", method: :delete, "data-confirm" => "本当に消しますか？" do %>
                Destroy
              <% end %>
            </td>

            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="contaice">
  <div class="row">
    <div class="px-3 mx-auto">
      <h1>Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!!</h1>
      <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
      <p>you can share and exchange your opinions, inpressions, and emotions</p>
      <p>about various books!</p>
      <div class="row">
        <%= link_to 'Log in', new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
      </div>
      <div class="row">
        <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li>
                <%= link_to user_path(current_user), class: "nav-link text-light" do %>
                  <i class="fas fa-home"></i> Home
                <% end %>
              </li>
              <li>
                <%= link_to users_path, class: "nav-link text-light" do %>
                  <i class="fas fa-users"></i> Users
                <% end %>
              </li>
              <li>
                <%= link_to books_path, class: "nav-link text-light" do %>
                  <i class="fas fa-book-open"></i> Books
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, class: "nav-link text-light", method: :delete do %>
                  <i class="fas fa-sign-out-alt"></i> Log out
                <% end %>
              </li>
            <% else %>
              <li>
                <%= link_to root_path, class: "nav-link text-light" do %>
                  <i class="fas fa-home"></i> Home
                <% end %>
              </li>
              <li>
                <%= link_to about_path, class: "nav-link text-light" do %>
                  <i class="fas fa-link"></i> About
                <% end %>
              </li>
              <li>
                <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
                  <i class="fas fa-user-plus"></i> Sign up
                <% end %>
              </li>
              <li>
                <%= link_to new_user_session_path, class: "nav-link text-light" do %>
                  <i class="fas fa-sign-in-alt"></i> Log in
                <% end %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
      <main>
         <%= flash[:notice] %>
         <%= yield %>
       </main>
       <footer>
         <div class="container mt-5">
           <div class="row">
             <div class="mx-auto">
                <p>CopyRight Infratop.inc</p>
             </div>
           </div>
         </div>
       </footer>
    </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      
      <% if @user.errors.any? %>
        <%= @user.errors.count %>errors prohibited this obj from being saved:
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      
      <%= form_with model: @user do |f| %>
        <label for="inputName">Name</label><br>
        <%= f.text_field :name, autofocus: true, id:"inqutName"%><br>
        <label for="inqutImage">Image</label><br>
        <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %><br>
        <label for="inputIntroduction">Introduction</label><br>
        <%= f.text_field :introduction, autofocus: true, id:"inputIntroduction"%><br>
        <%= f.submit "Update User", class: "btn btn-secondary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'books/list', user:@user, book:@book %>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table>
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td><%= image_tag user.get_profile_image %></td>
            <td><%= user.name %></td>
            <td><%= link_to "Show",user_path(user.id) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= render 'books/list', user:@user, book:@book %>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user.id) do %>
                <%= image_tag @user.get_profile_image %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>